-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.businesses
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    sector character varying(100) COLLATE pg_catalog."default",
    subscription_plan character varying(50) COLLATE pg_catalog."default" DEFAULT 'trial'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT businesses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.contact_messages
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    company character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT contact_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.followups
(
    id serial NOT NULL,
    lead_id integer,
    scheduled_at timestamp without time zone NOT NULL,
    sent boolean DEFAULT false,
    outcome text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT followups_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lead_messages
(
    id serial NOT NULL,
    lead_id integer,
    content text COLLATE pg_catalog."default" NOT NULL,
    sent_by character varying(100) COLLATE pg_catalog."default",
    ai_generated boolean DEFAULT false,
    sent_at timestamp without time zone DEFAULT now(),
    CONSTRAINT lead_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.leads
(
    id serial NOT NULL,
    business_id integer,
    client_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    phone character varying(50) COLLATE pg_catalog."default",
    inquiry_text text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'new'::character varying,
    close_probability integer DEFAULT 0,
    product_id integer,
    quantity integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT leads_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id serial NOT NULL,
    user_id integer,
    type character varying(100) COLLATE pg_catalog."default",
    message text COLLATE pg_catalog."default",
    read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id serial NOT NULL,
    business_id integer,
    supplier_id integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    category character varying(100) COLLATE pg_catalog."default",
    current_stock integer DEFAULT 0,
    min_stock integer DEFAULT 5,
    price numeric(10, 2) DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.purchase_orders
(
    id serial NOT NULL,
    business_id integer,
    supplier_id integer,
    product_id integer,
    quantity integer NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    sent_at timestamp without time zone,
    confirmed_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    note text COLLATE pg_catalog."default" DEFAULT ''::text,
    CONSTRAINT purchase_orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stock_movements
(
    id serial NOT NULL,
    product_id integer,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
    note text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT stock_movements_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subscriptions
(
    id serial NOT NULL,
    business_id integer,
    plan character varying(50) COLLATE pg_catalog."default" NOT NULL,
    price numeric(10, 2) NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    start_date timestamp without time zone DEFAULT now(),
    CONSTRAINT subscriptions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.suppliers
(
    id serial NOT NULL,
    business_id integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    contact_name character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    business_id integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" DEFAULT 'employee'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    verification_code_expiry timestamp without time zone,
    reset_token_expiry timestamp without time zone,
    email_verified boolean DEFAULT true,
    verification_code character varying(6) COLLATE pg_catalog."default",
    reset_token character varying(255) COLLATE pg_catalog."default",
    reset_code character varying(6) COLLATE pg_catalog."default",
    reset_code_expiry timestamp without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.followups
    ADD CONSTRAINT followups_lead_id_fkey FOREIGN KEY (lead_id)
    REFERENCES public.leads (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lead_messages
    ADD CONSTRAINT lead_messages_lead_id_fkey FOREIGN KEY (lead_id)
    REFERENCES public.leads (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.leads
    ADD CONSTRAINT leads_business_id_fkey FOREIGN KEY (business_id)
    REFERENCES public.businesses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_business_id_fkey FOREIGN KEY (business_id)
    REFERENCES public.businesses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_supplier_id_fkey FOREIGN KEY (supplier_id)
    REFERENCES public.suppliers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.purchase_orders
    ADD CONSTRAINT purchase_orders_business_id_fkey FOREIGN KEY (business_id)
    REFERENCES public.businesses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.purchase_orders
    ADD CONSTRAINT purchase_orders_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.purchase_orders
    ADD CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id)
    REFERENCES public.suppliers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.stock_movements
    ADD CONSTRAINT stock_movements_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.subscriptions
    ADD CONSTRAINT subscriptions_business_id_fkey FOREIGN KEY (business_id)
    REFERENCES public.businesses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.suppliers
    ADD CONSTRAINT suppliers_business_id_fkey FOREIGN KEY (business_id)
    REFERENCES public.businesses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_business_id_fkey FOREIGN KEY (business_id)
    REFERENCES public.businesses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;